<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>inventory_sampling</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="inventory_analysis_interactive_dbh_files/libs/clipboard/clipboard.min.js"></script>
<script src="inventory_analysis_interactive_dbh_files/libs/quarto-html/quarto.js"></script>
<script src="inventory_analysis_interactive_dbh_files/libs/quarto-html/popper.min.js"></script>
<script src="inventory_analysis_interactive_dbh_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="inventory_analysis_interactive_dbh_files/libs/quarto-html/anchor.min.js"></script>
<link href="inventory_analysis_interactive_dbh_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="inventory_analysis_interactive_dbh_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="inventory_analysis_interactive_dbh_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="inventory_analysis_interactive_dbh_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="inventory_analysis_interactive_dbh_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#exercise-on-inventorying-sampling-plots" id="toc-exercise-on-inventorying-sampling-plots" class="nav-link active" data-scroll-target="#exercise-on-inventorying-sampling-plots">Exercise on Inventorying (Sampling, Plots, …)</a></li>
  <li><a href="#i.-what-is-this-about" id="toc-i.-what-is-this-about" class="nav-link" data-scroll-target="#i.-what-is-this-about">I. What Is This About?</a></li>
  <li><a href="#ii.-lets-get-started-loading-and-inspecting-the-data" id="toc-ii.-lets-get-started-loading-and-inspecting-the-data" class="nav-link" data-scroll-target="#ii.-lets-get-started-loading-and-inspecting-the-data">II. Let’s Get Started: Loading and Inspecting the Data</a></li>
  <li><a href="#iii.-statistics" id="toc-iii.-statistics" class="nav-link" data-scroll-target="#iii.-statistics">III. Statistics</a>
  <ul class="collapse">
  <li><a href="#the-distribution-and-what-it-means" id="toc-the-distribution-and-what-it-means" class="nav-link" data-scroll-target="#the-distribution-and-what-it-means">The Distribution and what it means:</a></li>
  </ul></li>
  <li><a href="#iv.-sampling-and-measurement-accuracy" id="toc-iv.-sampling-and-measurement-accuracy" class="nav-link" data-scroll-target="#iv.-sampling-and-measurement-accuracy">IV. Sampling and measurement accuracy</a>
  <ul class="collapse">
  <li><a href="#a" id="toc-a" class="nav-link" data-scroll-target="#a">a) Simple Random Sampling</a></li>
  <li><a href="#b-regular-grid" id="toc-b-regular-grid" class="nav-link" data-scroll-target="#b-regular-grid">b) regular grid</a></li>
  <li><a href="#c-measurement-accuracy" id="toc-c-measurement-accuracy" class="nav-link" data-scroll-target="#c-measurement-accuracy">c) Measurement accuracy</a></li>
  </ul></li>
  <li><a href="#some-questions-about-this-whole-script-for-you-to-answer" id="toc-some-questions-about-this-whole-script-for-you-to-answer" class="nav-link" data-scroll-target="#some-questions-about-this-whole-script-for-you-to-answer">Some questions about this whole script for you to answer:</a></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">inventory_sampling</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="exercise-on-inventorying-sampling-plots" class="level1">
<h1>Exercise on Inventorying (Sampling, Plots, …)</h1>
<p>This is an interactive R script (Quarto Document) designed to let you directly see the effects of coding and to make everything easier to follow.</p>
</section>
<section id="i.-what-is-this-about" class="level1">
<h1>I. What Is This About?</h1>
<p>In this exercise, we will deepen your knowledge of inventorying, focusing on the topic of forests.</p>
<p>Each chapter will guide you through the necessary steps, so by the end, you’ll be able to consider the pros and cons of the different approaches in your next inventory. This will help you decide on the right method for your application and make yourself aware of the potential pitfalls.</p>
<p>A chapter overview can be seen on the right side of the document. This is how it goes:</p>
<ol type="1">
<li>First, we’ll <strong>install and load the necessary packages</strong></li>
<li>then we’ll proceed to <strong>basic statistics</strong> on our dataset.</li>
<li>From there, we’ll move on to <strong>two possible</strong> types of sampling inventories: <a href="#a">simple-random-sampling</a> and <a href="#c">regular grid</a>.</li>
<li>At the end we will encounter a <strong>real scenario of a person doing an inventory</strong> with given plot locations.</li>
</ol>
</section>
<section id="ii.-lets-get-started-loading-and-inspecting-the-data" class="level1">
<h1>II. Let’s Get Started: Loading and Inspecting the Data</h1>
<p>For this exercise, we’ll need the following packages:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 36%">
<col style="width: 63%">
</colgroup>
<thead>
<tr class="header">
<th>Package</th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>sf</code></td>
<td>Provides simple features for handling and analyzing spatial data, making it easy to work with geometries.</td>
</tr>
<tr class="even">
<td><code>dplyr</code></td>
<td>A grammar of data manipulation that helps in data wrangling tasks such as filtering, selecting, and summarizing.</td>
</tr>
<tr class="odd">
<td><code>tmap</code></td>
<td>A package for thematic mapping, offering an easy way to create static and interactive maps.</td>
</tr>
<tr class="even">
<td><code>ggplot2</code></td>
<td>A powerful system for creating complex and layered graphics using the grammar of graphics.</td>
</tr>
<tr class="odd">
<td><code>units</code></td>
<td>Provides support for handling measurement units in R, ensuring unit-aware arithmetic and conversion.</td>
</tr>
<tr class="even">
<td><code>reshape2</code></td>
<td>Helps in transforming and reshaping data, particularly useful for converting between wide and long formats.</td>
</tr>
</tbody>
</table>
<p>Next, we will load our forest inventory (make sure to pay attention to the file path: no umlauts, no spaces/special characters). We have one geopackage holding two feature layers:</p>
<ul>
<li><p>the inventory data itself (point geometries)</p></li>
<li><p>the field extent (polygon)</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Read a specific layer from the GeoPackage</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>tree_inventory_data <span class="ot">&lt;-</span> <span class="fu">st_read</span>(<span class="st">"tree_inv_ike.gpkg"</span>, <span class="at">layer =</span> <span class="st">"datasheet_ecosense2023"</span>)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="co"># renaming a column that has (for whatever reason) a weird name</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>tree_inventory_data <span class="ot">&lt;-</span> tree_inventory_data <span class="sc">%&gt;%</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">plot =</span> ï..Plot)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="fu">setnames</span>(tree_inventory_data, <span class="fu">tolower</span>(<span class="fu">names</span>(tree_inventory_data)))</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>field_extent <span class="ot">&lt;-</span> <span class="fu">st_read</span>(<span class="st">"tree_inv_ike.gpkg"</span>, <span class="at">layer =</span> <span class="st">"field_extent"</span>)</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Transform from EPSG:4326 to EPSG:32632</span></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>tree_inventory_data <span class="ot">&lt;-</span> <span class="fu">st_transform</span>(tree_inventory_data, <span class="at">crs =</span> <span class="dv">32632</span>)</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>field_extent <span class="ot">&lt;-</span> <span class="fu">st_transform</span>(field_extent, <span class="at">crs =</span> <span class="dv">32632</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(tree_inventory_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Simple feature collection with 6 features and 10 fields
Geometry type: POINT
Dimension:     XY
Bounding box:  xmin: 416706.7 ymin: 5346834 xmax: 416715.8 ymax: 5346845
Projected CRS: WGS 84 / UTM zone 32N
  plot tree latitude longitude species  dbh       date field_8 name
1    1    1 48.26933  7.877596   Beech 19.0 2023-03-07    &lt;NA&gt;  1_1
2    1    2 48.26933  7.877594   Beech 10.4 2023-03-07    &lt;NA&gt;  1_2
3    1    3 48.26930  7.877539     Oak 44.6 2023-03-07    &lt;NA&gt;  1_3
4    1    4 48.26924  7.877602   Beech  9.7 2023-03-07    &lt;NA&gt;  1_4
5    1    5 48.26925  7.877635   Beech 17.3 2023-03-07    &lt;NA&gt;  1_5
6    1    6 48.26927  7.877661   Beech 11.4 2023-03-07    &lt;NA&gt;  1_6
                 desc                     geom
1   DBH: 19 cm ,Beech   POINT (416711 5346844)
2 DBH: 10.4 cm ,Beech POINT (416710.9 5346845)
3   DBH: 44.6 cm ,Oak POINT (416706.7 5346841)
4  DBH: 9.7 cm ,Beech POINT (416711.3 5346834)
5 DBH: 17.3 cm ,Beech POINT (416713.8 5346836)
6 DBH: 11.4 cm ,Beech POINT (416715.8 5346838)</code></pre>
</div>
</div>
<p>Here, we can see that we have 7 attribute fields and that the data is already projected (EPSG: <code>st_crs(tree_inventory_data)$epsg</code>). The field “geom” indicates that we have point objects (which makes sense for trees—everything is as expected).</p>
<p>Now, we could simply plot the data by Lon/Lat and color it by PlotID to see what has been done. This can be conveniently done with the “tmap” library.</p>
<p>A little tip: If you need more information about working with geospatial data in R, colleagues from the Geography department have designed a wonderful basic course (in german) on this topic. <strong>–&gt;</strong> <a href="https://thinking-spatial.org/courses/angewandte_geodatenverarbeitung/" class="uri">https://thinking-spatial.org/courses/angewandte_geodatenverarbeitung/</a></p>
<p>Feel free to ask us anytime if something is unclear! :)</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="inventory_analysis_interactive_dbh_files/figure-html/tmap-plot-plots-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>We see that we have 18 clusters here, some larger and some smaller.</p>
<p><strong>For clarification:</strong> In the table the clusters are called “plot”, which is not a forest plot in the forestry meaning. So this is simply the clustering/tiling here. To not be confused.</p>
<p>The total area of the forest section is approximately <strong>2.78</strong> hectares. Additionally, we have <strong>1521</strong> trees in total across these plots, and the average area of each cluster is approximately <strong>0.31</strong> hectares.</p>
<p>Now, let’s take a look at how they are colored by DBH (where we have thicker and thinner trunks) to get a visual impression, almost as if we were standing on-site:</p>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>Warning: The shape tree_inventory_data contains empty units.</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="inventory_analysis_interactive_dbh_files/figure-html/tmap-plot-DBH-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Additionally, let’s also examine the distribution of tree species. This will give you an initial indication of where a sampling inventory might make sense (keyword: representativeness).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot 2: Tree species where the same species share the same color</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>plot_species <span class="ot">&lt;-</span> <span class="fu">tm_shape</span>(tree_inventory_data) <span class="sc">+</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_dots</span>(<span class="at">col =</span> <span class="st">"species"</span>, </span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>          <span class="at">palette =</span> <span class="st">"Set1"</span>, <span class="co"># Use a qualitative palette for species</span></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>          <span class="at">size =</span> <span class="fl">0.2</span>, <span class="co"># Fixed point size for species plot</span></span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>          <span class="at">legend.size.show =</span> <span class="cn">FALSE</span>) <span class="sc">+</span> </span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_shape</span>(field_extent) <span class="sc">+</span></span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_borders</span>(<span class="at">col =</span> <span class="st">"red"</span>, <span class="at">lwd =</span> <span class="dv">1</span>) <span class="sc">+</span> </span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_graticules</span>(<span class="at">lines =</span> <span class="cn">TRUE</span>, <span class="at">labels.size =</span> <span class="fl">0.5</span>, <span class="at">col =</span> <span class="st">"gray60"</span>, <span class="at">n.x =</span> <span class="dv">4</span>, <span class="at">n.y =</span> <span class="dv">4</span>) <span class="sc">+</span></span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_layout</span>(<span class="at">legend.outside =</span> <span class="cn">TRUE</span>) <span class="sc">+</span> </span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_legend</span>(<span class="at">title =</span> <span class="st">"Tree Species"</span>)</span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Adjust layout to maximize map area</span></span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a><span class="fu">tm_layout</span>(</span>
<span id="cb5-15"><a href="#cb5-15" aria-hidden="true" tabindex="-1"></a>  <span class="at">frame =</span> <span class="cn">TRUE</span>,  <span class="co"># Remove plot frame</span></span>
<span id="cb5-16"><a href="#cb5-16" aria-hidden="true" tabindex="-1"></a>  <span class="at">outer.margins =</span> <span class="dv">0</span>,  <span class="co"># Remove outer margins</span></span>
<span id="cb5-17"><a href="#cb5-17" aria-hidden="true" tabindex="-1"></a>  <span class="at">inner.margins =</span> <span class="fl">0.02</span>,  <span class="co"># Minimize inner margins</span></span>
<span id="cb5-18"><a href="#cb5-18" aria-hidden="true" tabindex="-1"></a>  <span class="at">asp =</span> <span class="dv">0</span>  <span class="co"># Automatically adjust aspect ratio</span></span>
<span id="cb5-19"><a href="#cb5-19" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb5-20"><a href="#cb5-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-21"><a href="#cb5-21" aria-hidden="true" tabindex="-1"></a><span class="co"># Arrange both plots side by side</span></span>
<span id="cb5-22"><a href="#cb5-22" aria-hidden="true" tabindex="-1"></a><span class="fu">tmap_arrange</span>(plot_species, <span class="at">nrow =</span> <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: The shape tree_inventory_data contains empty units.</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="inventory_analysis_interactive_dbh_files/figure-html/tmap-plot-sidebyside-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Feel free to familiarize yourself with the data. Observe where each tree species is located, where there are thicker or thinner trunks, where there are gaps, and where many trees are close together, etc. Try changing parameters in the code chunks above (those are the code blocks) or implement your own visualization ideas (nothing too complex). Just play around a bit. This will help you get a feel for the data we have here, which will aid in your understanding moving forward.</p>
</section>
<section id="iii.-statistics" class="level1">
<h1>III. Statistics</h1>
<p>Now let’s turn our attention to the statistical part of this exercise (Hooray!). We will calculate metrics such as mean, median, mode, standard deviation, IQR, and the quantiles Q1, Q2, Q3 (25%, 50%, 75%), as well as the 5% and 95% quantiles:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculation of Central Tendency</span></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>mean_dbh <span class="ot">&lt;-</span> <span class="fu">mean</span>(tree_inventory_data<span class="sc">$</span>dbh, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)   <span class="co"># Mean</span></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>median_dbh <span class="ot">&lt;-</span> <span class="fu">median</span>(tree_inventory_data<span class="sc">$</span>dbh, <span class="at">na.rm =</span> <span class="cn">TRUE</span>) <span class="co"># Median</span></span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>mode_dbh <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(<span class="fu">names</span>(<span class="fu">sort</span>(<span class="fu">table</span>(tree_inventory_data<span class="sc">$</span>dbh), <span class="at">decreasing =</span> <span class="cn">TRUE</span>)[<span class="dv">1</span>])) <span class="co"># Mode (value that appears the most)</span></span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculation of Dispersion</span></span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a>sd_dbh <span class="ot">&lt;-</span> <span class="fu">sd</span>(tree_inventory_data<span class="sc">$</span>dbh, <span class="at">na.rm =</span> <span class="cn">TRUE</span>) <span class="co"># Standard Deviation</span></span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a>iqr_dbh <span class="ot">&lt;-</span> <span class="fu">IQR</span>(tree_inventory_data<span class="sc">$</span>dbh, <span class="at">na.rm =</span> <span class="cn">TRUE</span>) <span class="co"># Interquartile Range</span></span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculation of Quantiles</span></span>
<span id="cb7-13"><a href="#cb7-13" aria-hidden="true" tabindex="-1"></a>quantiles_dbh <span class="ot">&lt;-</span> <span class="fu">quantile</span>(tree_inventory_data<span class="sc">$</span>dbh, <span class="at">probs =</span> <span class="fu">c</span>(<span class="fl">0.05</span>, <span class="fl">0.25</span>, <span class="fl">0.5</span>, <span class="fl">0.75</span>, <span class="fl">0.95</span>), <span class="at">na.rm =</span> <span class="cn">TRUE</span>) <span class="co"># Q1, Q2, Q3</span></span>
<span id="cb7-14"><a href="#cb7-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-15"><a href="#cb7-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Display results</span></span>
<span id="cb7-16"><a href="#cb7-16" aria-hidden="true" tabindex="-1"></a>results <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb7-17"><a href="#cb7-17" aria-hidden="true" tabindex="-1"></a>  <span class="at">Mean =</span> mean_dbh,</span>
<span id="cb7-18"><a href="#cb7-18" aria-hidden="true" tabindex="-1"></a>  <span class="at">Median =</span> median_dbh,</span>
<span id="cb7-19"><a href="#cb7-19" aria-hidden="true" tabindex="-1"></a>  <span class="at">Mode =</span> mode_dbh,</span>
<span id="cb7-20"><a href="#cb7-20" aria-hidden="true" tabindex="-1"></a>  <span class="at">Standard_Deviation =</span> sd_dbh,</span>
<span id="cb7-21"><a href="#cb7-21" aria-hidden="true" tabindex="-1"></a>  <span class="at">IQR =</span> iqr_dbh,</span>
<span id="cb7-22"><a href="#cb7-22" aria-hidden="true" tabindex="-1"></a>  <span class="at">Q_05 =</span> quantiles_dbh[<span class="dv">1</span>],</span>
<span id="cb7-23"><a href="#cb7-23" aria-hidden="true" tabindex="-1"></a>  <span class="at">Q1 =</span> quantiles_dbh[<span class="dv">2</span>],</span>
<span id="cb7-24"><a href="#cb7-24" aria-hidden="true" tabindex="-1"></a>  <span class="at">Q2 =</span> quantiles_dbh[<span class="dv">3</span>],</span>
<span id="cb7-25"><a href="#cb7-25" aria-hidden="true" tabindex="-1"></a>  <span class="at">Q3 =</span> quantiles_dbh[<span class="dv">4</span>],</span>
<span id="cb7-26"><a href="#cb7-26" aria-hidden="true" tabindex="-1"></a>  <span class="at">Q_95 =</span> quantiles_dbh[<span class="dv">5</span>]</span>
<span id="cb7-27"><a href="#cb7-27" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb7-28"><a href="#cb7-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-29"><a href="#cb7-29" aria-hidden="true" tabindex="-1"></a><span class="co"># Remove row names for quantiles</span></span>
<span id="cb7-30"><a href="#cb7-30" aria-hidden="true" tabindex="-1"></a><span class="fu">rownames</span>(results) <span class="ot">&lt;-</span> <span class="cn">NULL</span></span>
<span id="cb7-31"><a href="#cb7-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-32"><a href="#cb7-32" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(results)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      Mean Median Mode Standard_Deviation  IQR Q_05 Q1 Q2   Q3 Q_95
1 22.72128     16    9           14.88639 25.9  6.5 10 16 35.9 48.9</code></pre>
</div>
</div>
<p>Tables are nice, but visualizations are better - therefore, let’s present it as a plot:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load necessary packages</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate minimum and maximum DBH</span></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>min_dbh <span class="ot">&lt;-</span> <span class="fu">min</span>(tree_inventory_data<span class="sc">$</span>dbh, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>max_dbh <span class="ot">&lt;-</span> <span class="fu">max</span>(tree_inventory_data<span class="sc">$</span>dbh, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a histogram with density plot and add Min/Max DBH in the title</span></span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(tree_inventory_data, <span class="fu">aes</span>(<span class="at">x =</span> dbh)) <span class="sc">+</span></span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> <span class="dv">2</span>, <span class="at">fill =</span> <span class="st">"lightblue"</span>, <span class="at">color =</span> <span class="st">"black"</span>, <span class="at">alpha =</span> <span class="fl">0.6</span>) <span class="sc">+</span></span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="fu">aes</span>(<span class="at">xintercept =</span> mean_dbh, <span class="at">color =</span> <span class="st">"Mean"</span>), <span class="at">linetype =</span> <span class="st">"dashed"</span>, <span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span> <span class="co"># Mean line</span></span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="fu">aes</span>(<span class="at">xintercept =</span> median_dbh, <span class="at">color =</span> <span class="st">"Median"</span>), <span class="at">linetype =</span> <span class="st">"dashed"</span>, <span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span> <span class="co"># Median line</span></span>
<span id="cb9-13"><a href="#cb9-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="fu">aes</span>(<span class="at">xintercept =</span> quantiles_dbh[<span class="dv">1</span>], <span class="at">color =</span> <span class="st">"Q05"</span>), <span class="at">linetype =</span> <span class="st">"dashed"</span>, <span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span> <span class="co"># 5% line</span></span>
<span id="cb9-14"><a href="#cb9-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="fu">aes</span>(<span class="at">xintercept =</span> quantiles_dbh[<span class="dv">2</span>], <span class="at">color =</span> <span class="st">"Q95"</span>), <span class="at">linetype =</span> <span class="st">"dashed"</span>, <span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span> <span class="co"># 95% line</span></span>
<span id="cb9-15"><a href="#cb9-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="fu">paste</span>(<span class="st">"Distribution of DBH [cm] (Min:"</span>, <span class="fu">round</span>(min_dbh, <span class="dv">2</span>), <span class="st">"Max:"</span>, <span class="fu">round</span>(max_dbh, <span class="dv">2</span>), <span class="st">")"</span>),</span>
<span id="cb9-16"><a href="#cb9-16" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Diameter at Breast Height (DBH)"</span>,</span>
<span id="cb9-17"><a href="#cb9-17" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Frequency"</span>) <span class="sc">+</span></span>
<span id="cb9-18"><a href="#cb9-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"Mean"</span> <span class="ot">=</span> <span class="st">"blue"</span>, <span class="st">"Median"</span> <span class="ot">=</span> <span class="st">"green"</span>, <span class="st">"Q05"</span> <span class="ot">=</span> <span class="st">"yellow"</span>, <span class="st">"Q95"</span> <span class="ot">=</span> <span class="st">"orange"</span>)) <span class="sc">+</span> <span class="co"># color</span></span>
<span id="cb9-19"><a href="#cb9-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb9-20"><a href="#cb9-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb9-21"><a href="#cb9-21" aria-hidden="true" tabindex="-1"></a>    <span class="at">legend.title =</span> <span class="fu">element_blank</span>(),          <span class="co"># Remove legend title</span></span>
<span id="cb9-22"><a href="#cb9-22" aria-hidden="true" tabindex="-1"></a>    <span class="at">legend.spacing.y =</span> <span class="fu">unit</span>(<span class="fl">0.5</span>, <span class="st">'cm'</span>),      <span class="co"># Increase vertical spacing between legend entries</span></span>
<span id="cb9-23"><a href="#cb9-23" aria-hidden="true" tabindex="-1"></a>    <span class="at">legend.key.height =</span> <span class="fu">unit</span>(<span class="dv">1</span>, <span class="st">'lines'</span>),    <span class="co"># Increase space around legend key</span></span>
<span id="cb9-24"><a href="#cb9-24" aria-hidden="true" tabindex="-1"></a>    <span class="at">legend.text =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">10</span>)    <span class="co"># Adjust text size for better readability</span></span>
<span id="cb9-25"><a href="#cb9-25" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="inventory_analysis_interactive_dbh_files/figure-html/plot-statistics-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load necessary packages</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate minimum and maximum DBH</span></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>min_dbh <span class="ot">&lt;-</span> <span class="fu">min</span>(tree_inventory_data<span class="sc">$</span>dbh, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>max_dbh <span class="ot">&lt;-</span> <span class="fu">max</span>(tree_inventory_data<span class="sc">$</span>dbh, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a histogram with density plot and add Min/Max DBH in the title</span></span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(tree_inventory_data, <span class="fu">aes</span>(<span class="at">x =</span> dbh, <span class="at">fill =</span> species)) <span class="sc">+</span></span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> <span class="dv">2</span>, <span class="at">color =</span> <span class="st">"white"</span>, <span class="at">alpha =</span> <span class="fl">0.6</span>, <span class="at">position =</span> <span class="st">"stack"</span>) <span class="sc">+</span></span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="fu">paste</span>(<span class="st">"Distribution of DBH by Species"</span>),</span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Diameter at Breast Height (DBH)"</span>,</span>
<span id="cb10-13"><a href="#cb10-13" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Frequency"</span>) <span class="sc">+</span></span>
<span id="cb10-14"><a href="#cb10-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_discrete</span>(<span class="at">name =</span> <span class="st">"Species"</span>) <span class="sc">+</span> <span class="co"># Legend for species</span></span>
<span id="cb10-15"><a href="#cb10-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb10-16"><a href="#cb10-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb10-17"><a href="#cb10-17" aria-hidden="true" tabindex="-1"></a>    <span class="at">legend.title =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb10-18"><a href="#cb10-18" aria-hidden="true" tabindex="-1"></a>    <span class="at">legend.spacing.y =</span> <span class="fu">unit</span>(<span class="fl">0.5</span>, <span class="st">'cm'</span>),</span>
<span id="cb10-19"><a href="#cb10-19" aria-hidden="true" tabindex="-1"></a>    <span class="at">legend.key.height =</span> <span class="fu">unit</span>(<span class="dv">1</span>, <span class="st">'lines'</span>),</span>
<span id="cb10-20"><a href="#cb10-20" aria-hidden="true" tabindex="-1"></a>    <span class="at">legend.text =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">10</span>)</span>
<span id="cb10-21"><a href="#cb10-21" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="inventory_analysis_interactive_dbh_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the area covered by the trunk for each tree</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>tree_inventory_data <span class="ot">&lt;-</span> tree_inventory_data <span class="sc">%&gt;%</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">trunk_area =</span> pi <span class="sc">*</span> (dbh <span class="sc">/</span> <span class="dv">200</span>)<span class="sc">^</span><span class="dv">2</span>)  <span class="co"># DBH in cm, area in square meters</span></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the total trunk area covered by all trees</span></span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>total_trunk_area <span class="ot">&lt;-</span> <span class="fu">sum</span>(tree_inventory_data<span class="sc">$</span>trunk_area, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the total trunk area</span></span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">"Total trunk area: "</span>, <span class="fu">round</span>(total_trunk_area, <span class="dv">2</span>), <span class="st">"m2"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Total trunk area:  87.95 m2"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the percentage of the total area covered by trees</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>percentage_covered_by_trees <span class="ot">&lt;-</span> (total_trunk_area <span class="sc">/</span> <span class="fu">st_area</span>(field_extent)) <span class="sc">*</span> <span class="dv">100</span></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the percentage</span></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">"Percentage of total area covered by tree trunks:"</span>, <span class="fu">round</span>(percentage_covered_by_trees, <span class="dv">2</span>), <span class="st">"%"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Percentage of total area covered by tree trunks: 0.32 %"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Print m2/ha occupied by the trees (forestry measure)</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">"Bestandsgrundflaeche/Basal area: "</span>, <span class="fu">round</span>(total_trunk_area<span class="sc">/</span>(<span class="fu">st_area</span>(field_extent) <span class="sc">/</span> <span class="dv">10000</span>), <span class="dv">2</span>), <span class="st">"m2/ha"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Bestandsgrundflaeche/Basal area:  31.68 m2/ha"</code></pre>
</div>
</div>
<p><strong>Take some time to think</strong> about what this distribution tells us. It would be best to discuss this briefly (or in groups).</p>
<p>(Thought prompts: Bimodal, Mean vs Median –&gt; Meaning?, Q05 and Q95, high standard deviation, trunk area, …)</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>no, do not scroll down, think…</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>got you scrolling down (already thought about it?)</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>.</p>
<p>ok, now you can explore further :)</p>
<section id="the-distribution-and-what-it-means" class="level3">
<h3 class="anchored" data-anchor-id="the-distribution-and-what-it-means">The Distribution and what it means:</h3>
<ol type="1">
<li><p><strong>Mean (22.72):</strong> This is the average value across all measurements in your dataset, which gives you a general idea of the “central” point but can be skewed by outliers.</p></li>
<li><p><strong>Median (16):</strong> The median represents the middle value of the dataset, showing that half of the data values are above and half are below this number. Since the median is lower than the mean, this suggests a <em>right-skewed</em> distribution (a few higher values pulling the mean up).</p></li>
<li><p><strong>Mode (9):</strong> The mode is the most frequently occurring value, which indicates the most common measurement in your data. A mode lower than both the mean and median further supports the right-skew.</p></li>
<li><p><strong>Standard Deviation (14.89):</strong> This measures the spread of the data around the mean. A high standard deviation suggests that the data points are quite spread out, indicating variability in tree measurements.</p></li>
<li><p><strong>IQR (25.9):</strong> The interquartile range (Q3 - Q1) measures the spread of the middle 50% of the data, which helps identify the range of typical values and can signal the presence of outliers. An IQR of 25.9, larger than the median, suggests a wide range in the data.</p></li>
<li><p><strong>Q_05 (6.5):</strong> The 5th percentile tells us the value below which 5% of the observations fall, indicating that most of the data is higher than this value and giving us a sense of the lower tail.</p></li>
<li><p><strong>Q1 (10), Q2 (16), Q3 (35.9):</strong> These quartiles break the data into quarters. The data is relatively spread out, with a large jump from Q2 (the median) to Q3, which further suggests skewness.</p></li>
<li><p><strong>Q_95 (48.9):</strong> The 95th percentile tells us that only 5% of the data is above this value, which highlights the extreme values in the upper range of your data.</p></li>
</ol>
<p>In summary, this distribution is <em>right-skewed</em> (as indicated by the mean &gt; median &gt; mode) and has a high degree of variability (large standard deviation and IQR). There are likely a few very large trees (or values) that create a long right tail. This shape suggests wide range of tree sizes.</p>
<p>This statistical analysis of DBH can help inform forest management practices, such as assessing tree growth, planning for harvest, or understanding species composition and health.</p>
</section>
</section>
<section id="iv.-sampling-and-measurement-accuracy" class="level1">
<h1>IV. Sampling and measurement accuracy</h1>
<p>Now that we’ve examined the data, let’s move forward to the actual topic of sampling.</p>
<p>We will use 2 types of sampling methods and, in the end, compare the basal area from the “real” inventory with the different sampling methods.</p>
<p>We will use the following methods:</p>
<ul>
<li><p><strong>Simple random sampling</strong>: We randomly select trees from random plots and scale up the results.</p></li>
<li><p><strong>Regular grid</strong>: We create a simple grid with regular intervals and scale up the results.</p></li>
</ul>
<p>You can already start thinking about the advantages and disadvantages, but more on that later!</p>
<section id="a" class="level2">
<h2 class="anchored" data-anchor-id="a">a) Simple Random Sampling</h2>
<p>Let’s turn our attention to sampling. Suppose we use simple random sampling for the first case, randomly distributing points and recording trees within a 12 m radius. Would this reflect the “true” DBH and basal area statistics? How often are we off, and by how much? Let’s find out…</p>
<p>The steps in R are as follows:</p>
<ol type="1">
<li><p>Set parameters for the sampling.</p></li>
<li><p>Use a “for loop” to simulate multiple iterations.</p></li>
<li><p>Random points → Buffer → Clip → Intersection → calculate statistics.</p></li>
<li><p>Visualize the results.</p></li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(sf)</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Set the parameters for the simulation</span></span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>num_samples <span class="ot">&lt;-</span> <span class="dv">100</span> <span class="co"># Number of repetitions</span></span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>num_points <span class="ot">&lt;-</span> <span class="dv">10</span>   <span class="co"># Number of random points</span></span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Store the CRS of the tree_inventory_data</span></span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a>tree_crs <span class="ot">&lt;-</span> <span class="fu">st_crs</span>(tree_inventory_data)</span>
<span id="cb17-11"><a href="#cb17-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-12"><a href="#cb17-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Total area of the inventory</span></span>
<span id="cb17-13"><a href="#cb17-13" aria-hidden="true" tabindex="-1"></a>total_area <span class="ot">&lt;-</span> <span class="fu">st_area</span>(field_extent)</span>
<span id="cb17-14"><a href="#cb17-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-15"><a href="#cb17-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Empty list to store results</span></span>
<span id="cb17-16"><a href="#cb17-16" aria-hidden="true" tabindex="-1"></a>results_list <span class="ot">&lt;-</span> <span class="fu">vector</span>(<span class="st">"list"</span>, num_samples)</span>
<span id="cb17-17"><a href="#cb17-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-18"><a href="#cb17-18" aria-hidden="true" tabindex="-1"></a><span class="co"># Fix geometries to avoid intersection errors</span></span>
<span id="cb17-19"><a href="#cb17-19" aria-hidden="true" tabindex="-1"></a>field_extent <span class="ot">&lt;-</span> <span class="fu">st_make_valid</span>(field_extent)</span>
<span id="cb17-20"><a href="#cb17-20" aria-hidden="true" tabindex="-1"></a>field_extent <span class="ot">&lt;-</span> <span class="fu">st_simplify</span>(field_extent, <span class="at">dTolerance =</span> <span class="fl">0.0001</span>)</span>
<span id="cb17-21"><a href="#cb17-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-22"><a href="#cb17-22" aria-hidden="true" tabindex="-1"></a><span class="co"># Perform the simulation</span></span>
<span id="cb17-23"><a href="#cb17-23" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>num_samples) {</span>
<span id="cb17-24"><a href="#cb17-24" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Generate random points within the field_extent</span></span>
<span id="cb17-25"><a href="#cb17-25" aria-hidden="true" tabindex="-1"></a>  random_points <span class="ot">&lt;-</span> <span class="fu">st_sample</span>(field_extent, <span class="at">size =</span> num_points, <span class="at">type =</span> <span class="st">"random"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb17-26"><a href="#cb17-26" aria-hidden="true" tabindex="-1"></a>    <span class="fu">st_as_sf</span>() <span class="sc">%&gt;%</span></span>
<span id="cb17-27"><a href="#cb17-27" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">id =</span> <span class="fu">row_number</span>()) <span class="sc">%&gt;%</span></span>
<span id="cb17-28"><a href="#cb17-28" aria-hidden="true" tabindex="-1"></a>    <span class="fu">st_set_crs</span>(<span class="fu">st_crs</span>(field_extent)) <span class="sc">%&gt;%</span>  <span class="co"># Set the CRS of field_extent</span></span>
<span id="cb17-29"><a href="#cb17-29" aria-hidden="true" tabindex="-1"></a>    <span class="fu">st_transform</span>(tree_crs)  <span class="co"># Transform the CRS to that of tree_inventory_data</span></span>
<span id="cb17-30"><a href="#cb17-30" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb17-31"><a href="#cb17-31" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Create a buffer of 12 m around each point and combine with st_union() to avoid overlaps</span></span>
<span id="cb17-32"><a href="#cb17-32" aria-hidden="true" tabindex="-1"></a>  buffered_points <span class="ot">&lt;-</span> random_points <span class="sc">%&gt;%</span></span>
<span id="cb17-33"><a href="#cb17-33" aria-hidden="true" tabindex="-1"></a>    <span class="fu">st_buffer</span>(<span class="at">dist =</span> <span class="dv">12</span>) <span class="sc">%&gt;%</span></span>
<span id="cb17-34"><a href="#cb17-34" aria-hidden="true" tabindex="-1"></a>    <span class="fu">st_union</span>() <span class="sc">%&gt;%</span></span>
<span id="cb17-35"><a href="#cb17-35" aria-hidden="true" tabindex="-1"></a>    <span class="fu">st_make_valid</span>() <span class="sc">%&gt;%</span>     <span class="co"># Ensure buffered points are valid</span></span>
<span id="cb17-36"><a href="#cb17-36" aria-hidden="true" tabindex="-1"></a>    <span class="fu">st_simplify</span>(<span class="at">dTolerance =</span> <span class="fl">0.0001</span>)  <span class="co"># Remove duplicate vertices</span></span>
<span id="cb17-37"><a href="#cb17-37" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb17-38"><a href="#cb17-38" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Clip the buffered points to the field_extent</span></span>
<span id="cb17-39"><a href="#cb17-39" aria-hidden="true" tabindex="-1"></a>  clipped_buffers <span class="ot">&lt;-</span> <span class="fu">st_intersection</span>(buffered_points, field_extent)</span>
<span id="cb17-40"><a href="#cb17-40" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-41"><a href="#cb17-41" aria-hidden="true" tabindex="-1"></a>  buffer_area <span class="ot">&lt;-</span> <span class="fu">st_area</span>(clipped_buffers)</span>
<span id="cb17-42"><a href="#cb17-42" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb17-43"><a href="#cb17-43" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Intersection of trees with the buffered points</span></span>
<span id="cb17-44"><a href="#cb17-44" aria-hidden="true" tabindex="-1"></a>  sampled_trees <span class="ot">&lt;-</span> tree_inventory_data <span class="sc">%&gt;%</span></span>
<span id="cb17-45"><a href="#cb17-45" aria-hidden="true" tabindex="-1"></a>    <span class="fu">st_transform</span>(tree_crs) <span class="sc">%&gt;%</span>  <span class="co"># Ensure the CRS matches</span></span>
<span id="cb17-46"><a href="#cb17-46" aria-hidden="true" tabindex="-1"></a>    <span class="fu">st_make_valid</span>() <span class="sc">%&gt;%</span>  <span class="co"># Ensure valid geometries for tree data</span></span>
<span id="cb17-47"><a href="#cb17-47" aria-hidden="true" tabindex="-1"></a>    <span class="fu">st_intersection</span>(clipped_buffers)</span>
<span id="cb17-48"><a href="#cb17-48" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb17-49"><a href="#cb17-49" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Check if there are trees</span></span>
<span id="cb17-50"><a href="#cb17-50" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (<span class="fu">nrow</span>(sampled_trees) <span class="sc">&gt;</span> <span class="dv">0</span>) {</span>
<span id="cb17-51"><a href="#cb17-51" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Summarize results</span></span>
<span id="cb17-52"><a href="#cb17-52" aria-hidden="true" tabindex="-1"></a>    basal_area_sampled <span class="ot">&lt;-</span> <span class="fu">sum</span>(pi <span class="sc">*</span> (sampled_trees<span class="sc">$</span>dbh <span class="sc">/</span> <span class="dv">200</span>)<span class="sc">^</span><span class="dv">2</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>) <span class="sc">/</span> buffer_area <span class="sc">*</span> <span class="dv">10000</span></span>
<span id="cb17-53"><a href="#cb17-53" aria-hidden="true" tabindex="-1"></a>    mean_dbh <span class="ot">&lt;-</span> <span class="fu">mean</span>(sampled_trees<span class="sc">$</span>dbh, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb17-54"><a href="#cb17-54" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb17-55"><a href="#cb17-55" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Calculate the area of the buffered region (already without overlaps and within the field_extent)</span></span>
<span id="cb17-56"><a href="#cb17-56" aria-hidden="true" tabindex="-1"></a>    buffer_area <span class="ot">&lt;-</span> <span class="fu">st_area</span>(clipped_buffers)</span>
<span id="cb17-57"><a href="#cb17-57" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb17-58"><a href="#cb17-58" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Calculate the extrapolated basal area to the total area</span></span>
<span id="cb17-59"><a href="#cb17-59" aria-hidden="true" tabindex="-1"></a>    basal_area_proportional <span class="ot">&lt;-</span> <span class="fu">drop_units</span>(basal_area_sampled)</span>
<span id="cb17-60"><a href="#cb17-60" aria-hidden="true" tabindex="-1"></a>  } <span class="cf">else</span> {</span>
<span id="cb17-61"><a href="#cb17-61" aria-hidden="true" tabindex="-1"></a>    <span class="co"># If no trees are found, set the results to NA</span></span>
<span id="cb17-62"><a href="#cb17-62" aria-hidden="true" tabindex="-1"></a>    basal_area_proportional <span class="ot">&lt;-</span> <span class="cn">NA</span></span>
<span id="cb17-63"><a href="#cb17-63" aria-hidden="true" tabindex="-1"></a>    mean_dbh <span class="ot">&lt;-</span> <span class="cn">NA</span></span>
<span id="cb17-64"><a href="#cb17-64" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb17-65"><a href="#cb17-65" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb17-66"><a href="#cb17-66" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Store results in the list</span></span>
<span id="cb17-67"><a href="#cb17-67" aria-hidden="true" tabindex="-1"></a>  results_list[[i]] <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">basal_area_proportional =</span> basal_area_proportional, <span class="at">mean_dbh =</span> mean_dbh, <span class="at">count =</span> <span class="fu">nrow</span>(sampled_trees))</span>
<span id="cb17-68"><a href="#cb17-68" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb17-69"><a href="#cb17-69" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Plot only for the first iteration as an example of what is happening here</span></span>
<span id="cb17-70"><a href="#cb17-70" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (i <span class="sc">==</span> <span class="dv">1</span>) {</span>
<span id="cb17-71"><a href="#cb17-71" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb17-72"><a href="#cb17-72" aria-hidden="true" tabindex="-1"></a>      <span class="fu">geom_sf</span>(<span class="at">data =</span> field_extent, <span class="at">fill =</span> <span class="st">"lightgrey"</span>, <span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span> <span class="co"># Field extent</span></span>
<span id="cb17-73"><a href="#cb17-73" aria-hidden="true" tabindex="-1"></a>      <span class="fu">geom_sf</span>(<span class="at">data =</span> sampled_trees, <span class="at">color =</span> <span class="st">"green"</span>, <span class="at">size =</span> <span class="dv">2</span>) <span class="sc">+</span>      <span class="co"># Sampled trees</span></span>
<span id="cb17-74"><a href="#cb17-74" aria-hidden="true" tabindex="-1"></a>      <span class="fu">geom_sf</span>(<span class="at">data =</span> random_points, <span class="at">color =</span> <span class="st">"blue"</span>, <span class="at">size =</span> <span class="dv">3</span>) <span class="sc">+</span>       <span class="co"># Random points</span></span>
<span id="cb17-75"><a href="#cb17-75" aria-hidden="true" tabindex="-1"></a>      <span class="fu">geom_sf</span>(<span class="at">data =</span> clipped_buffers, <span class="at">fill =</span> <span class="cn">NA</span>, <span class="at">color =</span> <span class="st">"red"</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>) <span class="sc">+</span> <span class="co"># Buffered area (clipped)</span></span>
<span id="cb17-76"><a href="#cb17-76" aria-hidden="true" tabindex="-1"></a>      <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Sample Points and Trees in Field Extent"</span>,</span>
<span id="cb17-77"><a href="#cb17-77" aria-hidden="true" tabindex="-1"></a>           <span class="at">subtitle =</span> <span class="st">"Iteration 1"</span>,</span>
<span id="cb17-78"><a href="#cb17-78" aria-hidden="true" tabindex="-1"></a>           <span class="at">x =</span> <span class="st">"Longitude"</span>, <span class="at">y =</span> <span class="st">"Latitude"</span>) <span class="sc">+</span></span>
<span id="cb17-79"><a href="#cb17-79" aria-hidden="true" tabindex="-1"></a>      <span class="fu">theme_minimal</span>()</span>
<span id="cb17-80"><a href="#cb17-80" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb17-81"><a href="#cb17-81" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Show the plot</span></span>
<span id="cb17-82"><a href="#cb17-82" aria-hidden="true" tabindex="-1"></a>    <span class="fu">print</span>(<span class="fu">last_plot</span>())</span>
<span id="cb17-83"><a href="#cb17-83" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb17-84"><a href="#cb17-84" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="inventory_analysis_interactive_dbh_files/figure-html/simple-random-sampling-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert results into a DataFrame</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>results_df <span class="ot">&lt;-</span> <span class="fu">bind_rows</span>(results_list)</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate deviations (e.g., standard deviations)</span></span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>final_results <span class="ot">&lt;-</span> results_df <span class="sc">%&gt;%</span></span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">basal_area_mean =</span> <span class="fu">mean</span>(basal_area_proportional, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">basal_area_sd =</span> <span class="fu">sd</span>(basal_area_proportional, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">mean_dbh_mean =</span> <span class="fu">mean</span>(mean_dbh, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">mean_dbh_sd =</span> <span class="fu">sd</span>(mean_dbh, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb18-11"><a href="#cb18-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">sample_count =</span> <span class="fu">sum</span>(count) <span class="co"># Total number of trees across all samples</span></span>
<span id="cb18-12"><a href="#cb18-12" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb18-13"><a href="#cb18-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-14"><a href="#cb18-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Output the results</span></span>
<span id="cb18-15"><a href="#cb18-15" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(final_results)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  basal_area_mean basal_area_sd mean_dbh_mean mean_dbh_sd sample_count
1        32.21559      3.304055      22.81597    1.211445        22033</code></pre>
</div>
</div>
<p>Above is an example of what is happening here. We take random points in our area, draw 12 m circles, and include all the trees that are contained within them. Then we calculate our statistics for DBH and basal area again.</p>
<p><strong>Result</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>true_basal_area <span class="ot">&lt;-</span> <span class="fu">drop_units</span>(<span class="fu">round</span>(total_trunk_area<span class="sc">/</span>(<span class="fu">st_area</span>(field_extent) <span class="sc">/</span> <span class="dv">10000</span>), <span class="dv">2</span>))</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot the results for basal area</span></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(results_df, <span class="fu">aes</span>(<span class="at">x =</span> basal_area_proportional)) <span class="sc">+</span></span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins =</span> <span class="dv">30</span>, <span class="at">fill =</span> <span class="st">"lightblue"</span>, <span class="at">color =</span> <span class="st">"white"</span>) <span class="sc">+</span></span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Distribution of Basal Area over 100 Samples"</span>, </span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Basal Area (m²/ha)"</span>, </span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Number of Samples"</span>) <span class="sc">+</span></span>
<span id="cb20-9"><a href="#cb20-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="fu">aes</span>(<span class="at">xintercept =</span> true_basal_area), <span class="at">color =</span> <span class="st">"red"</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>, <span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb20-10"><a href="#cb20-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">annotate</span>(<span class="st">"text"</span>, <span class="at">x =</span> true_basal_area, <span class="at">y =</span> <span class="dv">1</span>, </span>
<span id="cb20-11"><a href="#cb20-11" aria-hidden="true" tabindex="-1"></a>           <span class="at">label =</span> <span class="st">"True Basal Area"</span>, <span class="at">color =</span> <span class="st">"red"</span>, <span class="at">vjust =</span> <span class="sc">-</span><span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="inventory_analysis_interactive_dbh_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot the results for mean DBH</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(results_df, <span class="fu">aes</span>(<span class="at">x =</span> mean_dbh)) <span class="sc">+</span></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins =</span> <span class="dv">30</span>, <span class="at">fill =</span> <span class="st">"lightblue"</span>, <span class="at">color =</span> <span class="st">"white"</span>) <span class="sc">+</span></span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Distribution of Average DBH over 100 Samples"</span>, </span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Average DBH"</span>, </span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Number of Samples"</span>) <span class="sc">+</span></span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="fu">aes</span>(<span class="at">xintercept =</span> <span class="fu">mean</span>(tree_inventory_data<span class="sc">$</span>dbh, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)), <span class="at">color =</span> <span class="st">"red"</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>, <span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">annotate</span>(<span class="st">"text"</span>, <span class="at">x =</span> <span class="fu">mean</span>(tree_inventory_data<span class="sc">$</span>dbh, <span class="at">na.rm =</span> <span class="cn">TRUE</span>), <span class="at">y =</span> <span class="dv">1</span>, </span>
<span id="cb21-9"><a href="#cb21-9" aria-hidden="true" tabindex="-1"></a>           <span class="at">label =</span> <span class="st">"True DBH"</span>, <span class="at">color =</span> <span class="st">"red"</span>, <span class="at">vjust =</span> <span class="sc">-</span><span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="inventory_analysis_interactive_dbh_files/figure-html/unnamed-chunk-12-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>As we can see, the actual DBH and the basal area is <strong>often massively over- or underestimated</strong>.</p>
<p>Here we do not take into account that all tree species are represented — so it could be that you totally forget one or more tree species… And the random sampling might oversee clusters, or grab a site where almost no tree is located…</p>
<p>We can now adjust our parameters, such as using multiple points, a larger buffer around the trees → more effort, but probably more accurate results.</p>
<p>Feel free to try the following changes and run the script while noting the changes you observe. Do they meet your expectations? What is the behaviour? Think about it:</p>
<ul>
<li><p>Fewer/more inventory points (num_points)</p></li>
<li><p>Change the buffer (smaller, larger)</p></li>
</ul>
<hr>
</section>
<section id="b-regular-grid" class="level2">
<h2 class="anchored" data-anchor-id="b-regular-grid">b) regular grid</h2>
<p>The regular grid is probably the simplest approach. We set up a point grid within our area with a chosen interval and then measure the trees within a radius of, for example, 12 meters from each point. We then calculate the DBH and basal area statistics of the forest stand. It’s clear that this will also have a large variation compared to the “real” values – we will see!</p>
<p><strong>The steps are as follows:</strong></p>
<ol type="1">
<li><p>First, we create a grid with points at regular intervals.</p></li>
<li><p>Then we again draw buffers around these points and measure all the trees contained within for our sampling inventory.</p></li>
<li><p>Finally, we extrapolate this to the total area (extrapolate buffer areas).</p></li>
<li><p>We represent the variability in a heatmap, which is associated with various parameters (grid spacing, buffer radius).</p></li>
</ol>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>Warning: attribute variables are assumed to be spatially constant throughout
all geometries
Warning: attribute variables are assumed to be spatially constant throughout
all geometries</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Estimated total basal area for the entire area: 91.9317086470576"</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Real total basal area from tree inventory data: 87.9529350647786"</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="inventory_analysis_interactive_dbh_files/figure-html/regular-grid-example-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="inventory_analysis_interactive_dbh_files/figure-html/regular-grid-example-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>   Grid_Spacing Buffer_Distance Estimated_Basal_Area Real_Basal_Area
1            20               5             76.71997        87.95294
2            20               6             78.23972        87.95294
3            20               7             80.55500        87.95294
4            20               8             85.31014        87.95294
5            20               9             86.38860        87.95294
6            20              10             87.17936        87.95294
7            20              11             87.54571        87.95294
8            20              12             88.03056        87.95294
9            20              13             88.54348        87.95294
10           20              14             88.99004        87.95294
11           20              15             88.51516        87.95294
12           30               5             81.07615        87.95294
13           30               6             85.13602        87.95294
14           30               7             94.21109        87.95294
15           30               8             94.46350        87.95294
16           30               9             95.14739        87.95294
17           30              10             94.78485        87.95294
18           30              11             92.56969        87.95294
19           30              12             91.93171        87.95294
20           30              13             92.80589        87.95294
21           30              14             91.05644        87.95294
22           30              15             90.70849        87.95294
23           40               5            100.76192        87.95294
24           40               6            102.35514        87.95294
25           40               7             95.10728        87.95294
26           40               8             83.69519        87.95294
27           40               9             83.30192        87.95294
28           40              10             81.91708        87.95294
29           40              11             87.71671        87.95294
30           40              12             89.18204        87.95294
31           40              13             86.20868        87.95294
32           40              14             84.44615        87.95294
33           40              15             82.84916        87.95294
34           50               5            131.72170        87.95294
35           50               6            121.44497        87.95294
36           50               7            107.50928        87.95294
37           50               8             95.65856        87.95294
38           50               9             93.41775        87.95294
39           50              10             89.34878        87.95294
40           50              11             87.86767        87.95294
41           50              12             86.24907        87.95294
42           50              13             92.11078        87.95294
43           50              14             91.85294        87.95294
44           50              15             91.66194        87.95294</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>Warning in dcast(results, Buffer_Distance ~ Grid_Spacing, value.var =
"Estimated_Basal_Area"): The dcast generic in data.table has been passed a
data.frame and will attempt to redirect to the relevant reshape2 method; please
note that reshape2 is superseded and is no longer actively developed, and this
redirection is now deprecated. Please do this redirection yourself like
reshape2::dcast(results). In the next version, this warning will become an
error.</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in melt.default(heatmap_data, id.vars = "Buffer_Distance",
variable.name = "Grid_Spacing", : The melt generic in data.table has been
passed a data.frame and will attempt to redirect to the relevant reshape2
method; please note that reshape2 is superseded and is no longer actively
developed, and this redirection is now deprecated. To continue using melt
methods from reshape2 while both libraries are attached, e.g. melt.list, you
can prepend the namespace, i.e. reshape2::melt(heatmap_data). In the next
version, this warning will become an error.</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="inventory_analysis_interactive_dbh_files/figure-html/regular-grid-heatmap-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>As expected, we see that there is a large variation in the values depending on the choice of the buffer and the grid spacing. Of course, if the grid spacing and the buffer are chosen such that every tree is covered, we will get the correct basal area; however, this is no longer a sampling inventory…</p>
<hr>
</section>
<section id="c-measurement-accuracy" class="level2">
<h2 class="anchored" data-anchor-id="c-measurement-accuracy">c) Measurement accuracy</h2>
<p>This is the last chapter. You are almost done with the exercise.</p>
<p><strong>Real case scenario ahead:</strong></p>
<p>Now, think of taking measurements in the forest on a location where you know the exact coordinates. So let’s imagine that someone already took the effort of choosing “good” plots for your inventory and gave them to you. You imagine yourself navigating to these locations using your phone’s GNSS (Click this link: <a href="https://globalgpssystems.com/gnss/the-difference-between-gnss-and-gps-explained/" class="uri">https://globalgpssystems.com/gnss/the-difference-between-gnss-and-gps-explained/</a>) or maybe even a high accuracy GNSS-Tool. Then, in the forest, alone, you discover that your Signal is jumping back and forth and you can never be sure to be on the exact position you intended to go to. You start measuring, nonetheless. <strong>Position is position, right?</strong> At the end, you want to compare the results to previous years. In the office you notice, that all your locations are slightly off, some maybe a few metres… You are sweating because you now have in mind that it could be the case that you even didn’t consider all the trees measured in the past years… Don’t be scared - this is a common Problem.</p>
<p>Let’s simulate that specific scenario:</p>
<ol type="1">
<li>create a <strong>list of 10 known coordinates</strong> inside the field extent</li>
<li><strong>take measurements</strong> of the trees in a certain radius (10m) from these locations (clip the buffer by the field extent)</li>
<li>Plot these locations to get a visual feeling (first graph)</li>
<li><strong>calculate the statistics</strong> for your forest</li>
<li>do that in a <strong>loop 10 times by varying the position of the known coordinates by 2m</strong> every time in a random direction (to see the influence of a floating gps coordinate)</li>
<li>compare the results (second, third and fourth graph)</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load required libraries</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(sf)</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Function to generate random directions for GPS floating effect</span></span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a>shift_coordinates <span class="ot">&lt;-</span> <span class="cf">function</span>(coords, <span class="at">shift_dist =</span> <span class="dv">2</span>) {</span>
<span id="cb28-8"><a href="#cb28-8" aria-hidden="true" tabindex="-1"></a>  angle <span class="ot">&lt;-</span> <span class="fu">runif</span>(<span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">2</span> <span class="sc">*</span> pi)  <span class="co"># random direction in radians</span></span>
<span id="cb28-9"><a href="#cb28-9" aria-hidden="true" tabindex="-1"></a>  coords_shifted <span class="ot">&lt;-</span> <span class="fu">st_coordinates</span>(coords) <span class="sc">+</span></span>
<span id="cb28-10"><a href="#cb28-10" aria-hidden="true" tabindex="-1"></a>    shift_dist <span class="sc">*</span> <span class="fu">c</span>(<span class="fu">cos</span>(angle), <span class="fu">sin</span>(angle))  <span class="co"># move coordinates by 1.5m</span></span>
<span id="cb28-11"><a href="#cb28-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_sfc</span>(<span class="fu">st_point</span>(coords_shifted), <span class="at">crs =</span> <span class="fu">st_crs</span>(coords))</span>
<span id="cb28-12"><a href="#cb28-12" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb28-13"><a href="#cb28-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-14"><a href="#cb28-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Set up the initial 10 known coordinates inside the field extent</span></span>
<span id="cb28-15"><a href="#cb28-15" aria-hidden="true" tabindex="-1"></a><span class="co">#set.seed(42)  # For reproducibility</span></span>
<span id="cb28-16"><a href="#cb28-16" aria-hidden="true" tabindex="-1"></a>initial_coords <span class="ot">&lt;-</span> <span class="fu">st_sample</span>(field_extent, <span class="at">size =</span> <span class="dv">10</span>, <span class="at">type =</span> <span class="st">"random"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb28-17"><a href="#cb28-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_as_sf</span>() <span class="sc">%&gt;%</span></span>
<span id="cb28-18"><a href="#cb28-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_set_crs</span>(<span class="fu">st_crs</span>(field_extent))</span>
<span id="cb28-19"><a href="#cb28-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-20"><a href="#cb28-20" aria-hidden="true" tabindex="-1"></a><span class="co"># Perform a baseline measurement with the initial coordinates</span></span>
<span id="cb28-21"><a href="#cb28-21" aria-hidden="true" tabindex="-1"></a>buffered_points_initial <span class="ot">&lt;-</span> initial_coords <span class="sc">%&gt;%</span></span>
<span id="cb28-22"><a href="#cb28-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_buffer</span>(<span class="at">dist =</span> <span class="dv">10</span>) <span class="sc">%&gt;%</span></span>
<span id="cb28-23"><a href="#cb28-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_union</span>() <span class="sc">%&gt;%</span></span>
<span id="cb28-24"><a href="#cb28-24" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_intersection</span>(field_extent)  <span class="co"># Clip buffers by the field extent</span></span>
<span id="cb28-25"><a href="#cb28-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-26"><a href="#cb28-26" aria-hidden="true" tabindex="-1"></a><span class="co"># Ensure both datasets have the same CRS before intersection</span></span>
<span id="cb28-27"><a href="#cb28-27" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="fu">st_crs</span>(buffered_points_initial) <span class="sc">!=</span> <span class="fu">st_crs</span>(tree_inventory_data)) {</span>
<span id="cb28-28"><a href="#cb28-28" aria-hidden="true" tabindex="-1"></a>  tree_inventory_data <span class="ot">&lt;-</span> <span class="fu">st_transform</span>(tree_inventory_data, <span class="fu">st_crs</span>(buffered_points_initial))</span>
<span id="cb28-29"><a href="#cb28-29" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb28-30"><a href="#cb28-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-31"><a href="#cb28-31" aria-hidden="true" tabindex="-1"></a><span class="co"># Intersect trees with the initial buffers</span></span>
<span id="cb28-32"><a href="#cb28-32" aria-hidden="true" tabindex="-1"></a>sampled_trees_initial <span class="ot">&lt;-</span> tree_inventory_data <span class="sc">%&gt;%</span></span>
<span id="cb28-33"><a href="#cb28-33" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_intersection</span>(buffered_points_initial)</span>
<span id="cb28-34"><a href="#cb28-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-35"><a href="#cb28-35" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate statistics for the baseline measurement</span></span>
<span id="cb28-36"><a href="#cb28-36" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="fu">nrow</span>(sampled_trees_initial) <span class="sc">&gt;</span> <span class="dv">0</span>) {</span>
<span id="cb28-37"><a href="#cb28-37" aria-hidden="true" tabindex="-1"></a>  mean_dbh_initial <span class="ot">&lt;-</span> <span class="fu">mean</span>(sampled_trees_initial<span class="sc">$</span>dbh, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb28-38"><a href="#cb28-38" aria-hidden="true" tabindex="-1"></a>  total_basal_area_initial <span class="ot">&lt;-</span> <span class="fu">sum</span>(pi <span class="sc">*</span> (sampled_trees_initial<span class="sc">$</span>dbh <span class="sc">/</span> <span class="dv">200</span>)<span class="sc">^</span><span class="dv">2</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>) <span class="sc">/</span> <span class="fu">drop_units</span>(<span class="fu">st_area</span>(buffered_points_initial)) <span class="sc">*</span> <span class="dv">10000</span></span>
<span id="cb28-39"><a href="#cb28-39" aria-hidden="true" tabindex="-1"></a>} <span class="cf">else</span> {</span>
<span id="cb28-40"><a href="#cb28-40" aria-hidden="true" tabindex="-1"></a>  mean_dbh_initial <span class="ot">&lt;-</span> <span class="cn">NA</span></span>
<span id="cb28-41"><a href="#cb28-41" aria-hidden="true" tabindex="-1"></a>  total_basal_area_initial <span class="ot">&lt;-</span> <span class="cn">NA</span></span>
<span id="cb28-42"><a href="#cb28-42" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb28-43"><a href="#cb28-43" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-44"><a href="#cb28-44" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot the initial measurement for visual understanding</span></span>
<span id="cb28-45"><a href="#cb28-45" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb28-46"><a href="#cb28-46" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_sf</span>(<span class="at">data =</span> field_extent, <span class="at">fill =</span> <span class="st">"lightgrey"</span>, <span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb28-47"><a href="#cb28-47" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_sf</span>(<span class="at">data =</span> sampled_trees_initial, <span class="at">color =</span> <span class="st">"green"</span>, <span class="at">size =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb28-48"><a href="#cb28-48" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_sf</span>(<span class="at">data =</span> initial_coords, <span class="at">color =</span> <span class="st">"blue"</span>, <span class="at">size =</span> <span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb28-49"><a href="#cb28-49" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_sf</span>(<span class="at">data =</span> buffered_points_initial, <span class="at">fill =</span> <span class="cn">NA</span>, <span class="at">color =</span> <span class="st">"red"</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>) <span class="sc">+</span></span>
<span id="cb28-50"><a href="#cb28-50" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Buffer and Trees for Initial Coordinates"</span>, <span class="at">subtitle =</span> <span class="st">"Initial Measurement"</span>,</span>
<span id="cb28-51"><a href="#cb28-51" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Longitude"</span>, <span class="at">y =</span> <span class="st">"Latitude"</span>) <span class="sc">+</span></span>
<span id="cb28-52"><a href="#cb28-52" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="inventory_analysis_interactive_dbh_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Now let’s start the loop and <strong>collecting statistics for 10 different measurements</strong>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Define number of iterations (loop runs)</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>num_iterations <span class="ot">&lt;-</span> <span class="dv">10</span></span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Empty list to store results for each iteration</span></span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a>results_list <span class="ot">&lt;-</span> <span class="fu">vector</span>(<span class="st">"list"</span>, num_iterations)</span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Empty list to store species composition data for each iteration</span></span>
<span id="cb29-8"><a href="#cb29-8" aria-hidden="true" tabindex="-1"></a>composition_list <span class="ot">&lt;-</span> <span class="fu">vector</span>(<span class="st">"list"</span>, num_iterations)</span>
<span id="cb29-9"><a href="#cb29-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-10"><a href="#cb29-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Loop to shift coordinates and compute results</span></span>
<span id="cb29-11"><a href="#cb29-11" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>num_iterations) {</span>
<span id="cb29-12"><a href="#cb29-12" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb29-13"><a href="#cb29-13" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Shift coordinates slightly by 2 meters in a random direction</span></span>
<span id="cb29-14"><a href="#cb29-14" aria-hidden="true" tabindex="-1"></a>  shifted_coords <span class="ot">&lt;-</span> initial_coords <span class="sc">%&gt;%</span></span>
<span id="cb29-15"><a href="#cb29-15" aria-hidden="true" tabindex="-1"></a>    <span class="fu">rowwise</span>() <span class="sc">%&gt;%</span></span>
<span id="cb29-16"><a href="#cb29-16" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">x =</span> <span class="fu">shift_coordinates</span>(x))</span>
<span id="cb29-17"><a href="#cb29-17" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb29-18"><a href="#cb29-18" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Create buffers of 10m around the shifted coordinates</span></span>
<span id="cb29-19"><a href="#cb29-19" aria-hidden="true" tabindex="-1"></a>  buffered_points <span class="ot">&lt;-</span> shifted_coords <span class="sc">%&gt;%</span></span>
<span id="cb29-20"><a href="#cb29-20" aria-hidden="true" tabindex="-1"></a>    <span class="fu">st_buffer</span>(<span class="at">dist =</span> <span class="dv">10</span>) <span class="sc">%&gt;%</span></span>
<span id="cb29-21"><a href="#cb29-21" aria-hidden="true" tabindex="-1"></a>    <span class="fu">st_union</span>() <span class="sc">%&gt;%</span></span>
<span id="cb29-22"><a href="#cb29-22" aria-hidden="true" tabindex="-1"></a>    <span class="fu">st_intersection</span>(field_extent)  <span class="co"># Clip buffers by the field extent</span></span>
<span id="cb29-23"><a href="#cb29-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-24"><a href="#cb29-24" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Intersect trees with the buffers</span></span>
<span id="cb29-25"><a href="#cb29-25" aria-hidden="true" tabindex="-1"></a>  sampled_trees <span class="ot">&lt;-</span> tree_inventory_data <span class="sc">%&gt;%</span></span>
<span id="cb29-26"><a href="#cb29-26" aria-hidden="true" tabindex="-1"></a>    <span class="fu">st_intersection</span>(buffered_points)</span>
<span id="cb29-27"><a href="#cb29-27" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb29-28"><a href="#cb29-28" aria-hidden="true" tabindex="-1"></a>  <span class="co"># If there are trees in the buffer, calculate statistics</span></span>
<span id="cb29-29"><a href="#cb29-29" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (<span class="fu">nrow</span>(sampled_trees) <span class="sc">&gt;</span> <span class="dv">0</span>) {</span>
<span id="cb29-30"><a href="#cb29-30" aria-hidden="true" tabindex="-1"></a>    mean_dbh <span class="ot">&lt;-</span> <span class="fu">mean</span>(sampled_trees<span class="sc">$</span>dbh, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb29-31"><a href="#cb29-31" aria-hidden="true" tabindex="-1"></a>    total_basal_area <span class="ot">&lt;-</span> <span class="fu">sum</span>(pi <span class="sc">*</span> (sampled_trees<span class="sc">$</span>dbh <span class="sc">/</span> <span class="dv">200</span>)<span class="sc">^</span><span class="dv">2</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>) <span class="sc">/</span> <span class="fu">drop_units</span>(<span class="fu">st_area</span>(buffered_points)) <span class="sc">*</span> <span class="dv">10000</span></span>
<span id="cb29-32"><a href="#cb29-32" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb29-33"><a href="#cb29-33" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Count species and calculate percentages</span></span>
<span id="cb29-34"><a href="#cb29-34" aria-hidden="true" tabindex="-1"></a>    species_counts <span class="ot">&lt;-</span> <span class="fu">table</span>(sampled_trees<span class="sc">$</span>species)</span>
<span id="cb29-35"><a href="#cb29-35" aria-hidden="true" tabindex="-1"></a>    composition <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(species_counts)</span>
<span id="cb29-36"><a href="#cb29-36" aria-hidden="true" tabindex="-1"></a>    <span class="fu">colnames</span>(composition) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"species"</span>, <span class="st">"count"</span>)</span>
<span id="cb29-37"><a href="#cb29-37" aria-hidden="true" tabindex="-1"></a>    composition<span class="sc">$</span>iteration <span class="ot">&lt;-</span> i</span>
<span id="cb29-38"><a href="#cb29-38" aria-hidden="true" tabindex="-1"></a>    composition<span class="sc">$</span>percentage <span class="ot">&lt;-</span> (composition<span class="sc">$</span>count <span class="sc">/</span> <span class="fu">sum</span>(composition<span class="sc">$</span>count)) <span class="sc">*</span> <span class="dv">100</span></span>
<span id="cb29-39"><a href="#cb29-39" aria-hidden="true" tabindex="-1"></a>    composition_list[[i]] <span class="ot">&lt;-</span> composition</span>
<span id="cb29-40"><a href="#cb29-40" aria-hidden="true" tabindex="-1"></a>  } <span class="cf">else</span> {</span>
<span id="cb29-41"><a href="#cb29-41" aria-hidden="true" tabindex="-1"></a>    mean_dbh <span class="ot">&lt;-</span> <span class="cn">NA</span></span>
<span id="cb29-42"><a href="#cb29-42" aria-hidden="true" tabindex="-1"></a>    total_basal_area <span class="ot">&lt;-</span> <span class="cn">NA</span></span>
<span id="cb29-43"><a href="#cb29-43" aria-hidden="true" tabindex="-1"></a>    composition_list[[i]] <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">species =</span> <span class="cn">NA</span>, <span class="at">count =</span> <span class="cn">NA</span>, <span class="at">iteration =</span> i, <span class="at">percentage =</span> <span class="cn">NA</span>)</span>
<span id="cb29-44"><a href="#cb29-44" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb29-45"><a href="#cb29-45" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb29-46"><a href="#cb29-46" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Store results</span></span>
<span id="cb29-47"><a href="#cb29-47" aria-hidden="true" tabindex="-1"></a>  results_list[[i]] <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb29-48"><a href="#cb29-48" aria-hidden="true" tabindex="-1"></a>    <span class="at">iteration =</span> i,</span>
<span id="cb29-49"><a href="#cb29-49" aria-hidden="true" tabindex="-1"></a>    <span class="at">mean_dbh =</span> mean_dbh,</span>
<span id="cb29-50"><a href="#cb29-50" aria-hidden="true" tabindex="-1"></a>    <span class="at">total_basal_area =</span> total_basal_area,</span>
<span id="cb29-51"><a href="#cb29-51" aria-hidden="true" tabindex="-1"></a>    <span class="at">num_trees =</span> <span class="fu">nrow</span>(sampled_trees)</span>
<span id="cb29-52"><a href="#cb29-52" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb29-53"><a href="#cb29-53" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb29-54"><a href="#cb29-54" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-55"><a href="#cb29-55" aria-hidden="true" tabindex="-1"></a><span class="co"># Combine all results into a single dataframe</span></span>
<span id="cb29-56"><a href="#cb29-56" aria-hidden="true" tabindex="-1"></a>results_df <span class="ot">&lt;-</span> <span class="fu">bind_rows</span>(results_list)</span>
<span id="cb29-57"><a href="#cb29-57" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-58"><a href="#cb29-58" aria-hidden="true" tabindex="-1"></a><span class="co"># Add the baseline measurement to the results dataframe for comparison</span></span>
<span id="cb29-59"><a href="#cb29-59" aria-hidden="true" tabindex="-1"></a>baseline_df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb29-60"><a href="#cb29-60" aria-hidden="true" tabindex="-1"></a>  <span class="at">iteration =</span> <span class="dv">0</span>,</span>
<span id="cb29-61"><a href="#cb29-61" aria-hidden="true" tabindex="-1"></a>  <span class="at">mean_dbh =</span> mean_dbh_initial,</span>
<span id="cb29-62"><a href="#cb29-62" aria-hidden="true" tabindex="-1"></a>  <span class="at">total_basal_area =</span> total_basal_area_initial,</span>
<span id="cb29-63"><a href="#cb29-63" aria-hidden="true" tabindex="-1"></a>  <span class="at">num_trees =</span> <span class="fu">nrow</span>(sampled_trees_initial)</span>
<span id="cb29-64"><a href="#cb29-64" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb29-65"><a href="#cb29-65" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-66"><a href="#cb29-66" aria-hidden="true" tabindex="-1"></a>results_df <span class="ot">&lt;-</span> <span class="fu">bind_rows</span>(baseline_df, results_df)</span>
<span id="cb29-67"><a href="#cb29-67" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-68"><a href="#cb29-68" aria-hidden="true" tabindex="-1"></a><span class="co"># Combine all compositions into a single dataframe</span></span>
<span id="cb29-69"><a href="#cb29-69" aria-hidden="true" tabindex="-1"></a>composition_df <span class="ot">&lt;-</span> <span class="fu">bind_rows</span>(composition_list)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Let’s compare the results by plotting the statistics for <strong>DBH, Basal Area and Species composition</strong>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot the results for mean DBH</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(results_df, <span class="fu">aes</span>(<span class="at">x =</span> iteration)) <span class="sc">+</span></span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y =</span> mean_dbh), <span class="at">color =</span> <span class="st">"blue"</span>, <span class="at">size =</span> <span class="dv">1</span>, <span class="at">show.legend =</span> <span class="cn">TRUE</span>) <span class="sc">+</span></span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">y =</span> mean_dbh), <span class="at">color =</span> <span class="st">"blue"</span>, <span class="at">size =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> mean_dbh_initial, <span class="at">color =</span> <span class="st">"blue"</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>, <span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Mean DBH Across Iterations"</span>,</span>
<span id="cb30-7"><a href="#cb30-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Iteration (0 is baseline)"</span>, <span class="at">y =</span> <span class="st">"Mean DBH"</span>) <span class="sc">+</span></span>
<span id="cb30-8"><a href="#cb30-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="inventory_analysis_interactive_dbh_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot the results for total basal area</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(results_df, <span class="fu">aes</span>(<span class="at">x =</span> iteration)) <span class="sc">+</span></span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y =</span> total_basal_area), <span class="at">color =</span> <span class="st">"green"</span>, <span class="at">size =</span> <span class="dv">1</span>, <span class="at">show.legend =</span> <span class="cn">TRUE</span>) <span class="sc">+</span></span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">y =</span> total_basal_area), <span class="at">color =</span> <span class="st">"green"</span>, <span class="at">size =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> total_basal_area_initial, <span class="at">color =</span> <span class="st">"green"</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>, <span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Total Basal Area Across Iterations"</span>,</span>
<span id="cb31-7"><a href="#cb31-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Iteration (0 is baseline)"</span>, <span class="at">y =</span> <span class="st">"Total Basal Area (m²/ha)"</span>) <span class="sc">+</span></span>
<span id="cb31-8"><a href="#cb31-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="inventory_analysis_interactive_dbh_files/figure-html/unnamed-chunk-18-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot the composition of tree species across iterations</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(composition_df, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">factor</span>(iteration), <span class="at">y =</span> percentage, <span class="at">fill =</span> species)) <span class="sc">+</span></span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">"identity"</span>, <span class="at">position =</span> <span class="st">"fill"</span>) <span class="sc">+</span>  <span class="co"># Use position = "fill" for percentage stacking</span></span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Tree Species Composition Across Iterations"</span>,</span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Iteration"</span>, <span class="at">y =</span> <span class="st">"Percentage"</span>,</span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">fill =</span> <span class="st">"Species"</span>) <span class="sc">+</span></span>
<span id="cb32-7"><a href="#cb32-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb32-8"><a href="#cb32-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">labels =</span> scales<span class="sc">::</span><span class="fu">percent_format</span>(<span class="at">scale =</span> <span class="dv">100</span>)) <span class="sc">+</span>  <span class="co"># Format y-axis as percentage</span></span>
<span id="cb32-9"><a href="#cb32-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">45</span>, <span class="at">hjust =</span> <span class="dv">1</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="inventory_analysis_interactive_dbh_files/figure-html/unnamed-chunk-18-3.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>You can already guess that there is a slight variability in the tree measurements collected to given locations. Play around by varying the:</p>
<ul>
<li><p>buffer size</p></li>
<li><p>plot number</p></li>
<li><p>coordinate shifting</p></li>
</ul>
<p>and think about the different results.</p>
</section>
</section>
<section id="some-questions-about-this-whole-script-for-you-to-answer" class="level1">
<h1>Some questions about this whole script for you to answer:</h1>
<ol type="1">
<li><p>What does the distribution tell us about the forest? Is it homogeneous? Do we have extremes? Do all trees have about the same size?</p></li>
<li><p>When you think about the sampling and the obtained results, try and summarize the pros and cons of the <strong>simple random sampling</strong>:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>+</th>
<th>-</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td></td>
<td></td>
</tr>
<tr class="even">
<td></td>
<td></td>
</tr>
<tr class="odd">
<td></td>
<td></td>
</tr>
<tr class="even">
<td></td>
<td></td>
</tr>
<tr class="odd">
<td></td>
<td></td>
</tr>
<tr class="even">
<td></td>
<td></td>
</tr>
</tbody>
</table></li>
<li><p>Now give pros and cons using the <strong>regular grid</strong> method. Which one is more suitable? With which parameters?:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>+</th>
<th>-</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td></td>
<td></td>
</tr>
<tr class="even">
<td></td>
<td></td>
</tr>
<tr class="odd">
<td></td>
<td></td>
</tr>
<tr class="even">
<td></td>
<td></td>
</tr>
<tr class="odd">
<td></td>
<td></td>
</tr>
<tr class="even">
<td></td>
<td></td>
</tr>
</tbody>
</table></li>
<li><p>Which influence has the size of the plot (so the radius where you take measurements)?</p></li>
<li><p>Which influence has the number of plots you are measuring?</p></li>
<li><p>Would you repeat an inventory using simply your phone’s GNSS? Why yes? Why no?</p></li>
</ol>
<p>This whole exercise is meant to show you how susceptible such sampling inventories are to (sometimes large) errors compared to the true result.</p>
<p>So, as you have already learned in the lectures: <strong>Question the numbers!</strong></p>
<p>Feel free to experiment with the code, develop your own ideas or visualizations – this script is now complete!</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>